stylelint-prettier.js, test/prettierrc/default/.prettierrc, test/stylelint-prettier.test.js
The inferred parser does not take into account any overrides specified
in .prettierrc.
By not specifying a parser in the options, prettier shall still infer
the parser internally, at a point where overrides specified in
.prettierrc are resolved.
This means that users can specify parsers for custom file extensions
rather than be limited to the filename->parser mapping that prettier has
built-in.
Fixes #1
=> Don't force using the inferred parser

stylelint-prettier.js, test/stylelint-prettier.test.js
Hey! Thanks for this package 😸 
Right now, all options are passed automatically right from the `stylelint-prettier` rule into prettier itself.
That causes a warning if you pass something that is related to stylelint only, like `severity`, So the following line actually raises a warning:
```json
{
"rules": {
"prettier/prettier": [true, { "severity": "warning" }]
}
}
```
This warning can be avoided, so this PR fixes it by omitting `severity`. Figuring out which keys should be allowed may be problematic if Prettier will change its API, but I guess that `severity` is something that won't be there anyway because it's not a linter.
What do you think?
😸
=> Omit `severity` for removing the warning from prettier

stylelint-prettier.js, test/stylelint-prettier.test.js
Prior to this commit setting an explicit syntax when autofixing would
cause a crash as we were assuming we had access to values injected by
postcss-syntax at all times.
Check of the existence of the parser that postcss-syntax provides, and
if that is not present then use the one specified in the options
Fixes #8
//cc @lydell Can you give this branch a try to see if it fixes your issues?
We're still relying on an implementation detail of postcss-syntax (i.e. that it adds `root.source.syntax`), but I think this is the best I can do given the current stylelint API. Otherwise stylelint would have to expose `getPostcssResult` as part of its public API which feels like it opens up a large bag of worms.
=> Fix error when calling stylelint with --syntax and --fix

.travis.yml, package.json, stylelint-prettier.js, test/stylelint-prettier.test.js, yarn.lock
Minimum supported stylelint version remains at 9.2.1, but 9.5.0 is needed
for unit testing this
=> Report parsing errors instead of crashing

.eslintignore, .eslintrc.js, .github/CONTRIBUTING.md, .prettierignore, package.json, stylelint-prettier.js, test/fixtures/check.inert.html, test/fixtures/check.inert.js, test/fixtures/check.inert.md, test/fixtures/check.inert.vue, test/fixtures/check.invalid.css, test/fixtures/check.invalid.scss, test/fixtures/check.unparsable.js, test/fixtures/stylelint.config.js, test/stylelint-prettier-e2e.test.js, test/stylelint-prettier.test.js, yarn.lock
Stylelint 9.10.0 uses postcss-jsx to parse css-in-js solutions and postcss-html to parse vue/markdown/html files. These two together mean the embedded languages landscape is a lot cleaner than a few months ago in the days of 9.2.1.
However stylelint 9.9 to 9.10 changed how these embedded languages were passed into rules. In 9.9 the whole file content was available in `root.source.input` (i.e. a whole html or vue file, including all surrounding html tags tags). In 9.10 only the contents of style language fragments are available (i.e. only the content of each of the `<style>` tags gets passed to the rule).
This means that we can run stylelint with stylelint-prettier over these embedded language files, but it'll only prettify the style portions. If you're this interested in prettier then you …
=> Make sure we don't explode on Vue and css-in-js solutions

stylelint-prettier.js, test/stylelint-prettier.test.js
This PR fixes the incorrect EOL handling at the End of File on Windows #23.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#Return_value) `match `will return `null` if nothing matches. In this case, `trailingWhitespace[0]` accessed only the first character of `\r\n`.
I've added tests to cover those cases and prevent regression.
I've also applied the fix to the Repository https://github.com/rzontar/stylelint-prettier-cr/tree/fix and verified the results.
=> Correct EOL handling for UNIX and Windows

.travis.yml, .vscode/settings.json, package.json, stylelint-prettier.js, test/fixtures/check.inert.html, test/fixtures/check.inert.jsx, test/fixtures/check.inert.md, test/fixtures/check.inert.tsx, test/stylelint-prettier-e2e.test.js, yarn.lock
Kicking dev dependencies.
Add a few more tests for langs that support embeds.
Add config option to when getting file info so user defined parser overrides are taken into account.
Add an extra little safeguard against accidentally formatting css-in-js object literals (these should already be caught by the parser inference stuff
Dropping CI support for node 6 because of it is EOL. I'll keep supporting it in v1.x.
---
When I eventually cut a 2.x that increases the minimum versions of prettier and stylelint then I'll update engines to require a newer node version too (possibly 8, but that's EOL at the end of this month too).
=> Updates dev-deps and a few extra checks

test/stylelint-prettier-e2e.test.js
Stylelint doesn't always report errors in the same order. Avoid that
breaking tests by only checking one file per test case.
=> Avoid potentially flaky tests

package.json, stylelint-prettier.js, test/fixtures/check.inert.component.html, test/fixtures/check.inert.svelte, test/stylelint-prettier-e2e.test.js, yarn.lock
prettier already takes care of formatting these whole files, so skip
them, just like js/markdown/html/vue files (see #22)
With thanks to @JounQin who investigated this in #156
=> Skip processing angular and svelte files

.github/workflows/ci.yml, .vscode/settings.json, jest-setup.js, package.json, stylelint-prettier.js, test/fixtures/stylelint.config.js, test/stylelint-prettier-e2e.test.js, test/stylelint-prettier.test.js, yarn.lock
Technically our source code for v1.2.0 continues to work in stylelint v14 but v14 made
changes to how non-css syntaxes are parsed which makes it difficult to
test against v14 and older versions at the same time. So let's cut a v2 that only supports stylelint v14.
Version requirement bumps:
- Require stylelint >=14 (drop support for v9.5 - 13.x)
- Require prettier >=2 (drop support for v1)
- Require node 12 (drop support for node 10)
Other changes:
- Replace usage of `syntax` with `customSyntax`
- Specify a customSyntax when testing scss file content
- Define overrides for novel file types in the e2e fixture config
- Update dev dependencies
- Add CI matrix run for node 16
- Remove CI matrix runs for prettier v1,  node 8/10, stylelint 9.5/10/11/12/13
=> Version 2 - Drop support for old stylelint / prettier / node versions

stylelint-prettier.js
Minor doc issue I noticed trying to trace back a config issue by looking at the source for the plugin
=> chore: remove double word "the"

.eslintrc.js, .github/workflows/ci.yml, package.json, stylelint-prettier.js, test/stylelint-prettier-e2e.test.js, yarn.lock
Minimum supported Prettier version is v3.0.0
Minimum supported stylelint version is 15.8.0
- Use `await import()` instead of require.
- Use async (and now the only) versions of resolveConfig, getFileInfo and format
- Tweak jest/eslint configs to account for prettier using esmodules
=> Prettier v3 support

.github/workflows/ci.yml, package.json, stylelint-prettier.js, test/fixtures/stylelint.config.js, test/stylelint-prettier-e2e.test.js, yarn.lock
In the 3.0.0 release we skipped the svelte test as a new version of `prettier-plugin-svelte` that supported prettier v3 wasn't yet released. It's now released, and it has uncovered a small regression when dealing with ignored parsers.
This PR:
- Updates `prettier-plugin-svelte` and `svelte`
- Reenables the svelte e2e test
- Ensures that plugins are accounted for when determining what files should be ignored.
=> Reenable svelte test and fix parser inference for plugins

stylelint-prettier.js
Fixes #310.
Handle the case where `prettierRcOptions` returns null when no prettier config or editorconfig is present when curating a plugins list.
=> Handle case where no prettier config is present

package.json, stylelint-prettier.js, test/stylelint-prettier.test.js, yarn.lock
This allows formatters and editor plugins to show the range of problematic code
=> Add endIndex when reporting issues

package.json, stylelint-prettier.js, test/fixtures/check.inert.astro, test/fixtures/stylelint.config.js, test/stylelint-prettier-e2e.test.js, yarn.lock
Fixes #332 
Adds a test for astro components (which are currently failing to parse) then adds astro components to the parser blocklist (which causes the test to pass, as they are skipped).
Astro component files are similar to all of the other blocked component files in that they may contain styles as well as markup, and they just happen to cause errors in styles parsing (the same error as Svelte components actually), so I think its reasonable to skip them for the same reasons as the other component types.
=> Add astro components to parser blocklist

.eslintrc.cjs, index.js, test/stylelint-prettier-e2e.test.js
Closed https://github.com/prettier/stylelint-prettier/issues/354 
I'm not a styling guru. But at least I added a test demonstrating the bug, and added a description of the problem that this bug causes.
=> Fix prettier and other rules working at the same time

index.js, package.json, test/fixtures/check.invalid.less, test/fixtures/stylelint.config.js, test/stylelint-prettier-e2e.test.js, yarn.lock
Closed https://github.com/prettier/stylelint-prettier/issues/362
Less turned out to be a bit tricky, e.g. less mixins are transformed into _❝AtRule❞_ with an additional prop: https://github.com/shellscape/postcss-less?tab=readme-ov-file#mixins. As a result when converted to a string, mixins lost their original appearance.
I can assume that other formats are supported by postcss "more natively", and it could make the reverse conversion without additional options, so no tests failed in previous PR.
=> Fix work with less files after #360

test/stylelint-prettier-e2e.test.js
stylelint's e2e tests started failing in October per https://github.com/stylelint/stylelint-ecosystem-tester/issues/61
It looks like some node debug message is screwing the ability to parse the output of stderr when using `--json` as json, but the current message is highly truncated. I suspect this is new as a result of moving from node 20 to 22 for the the ecosystem tests.
I'm taking bets on it being a message regarding `require(esm)` usage in node_modules that will be silenced in the next v22 release - https://github.com/nodejs/node/pull/55217
The error we get is:
>  error: `Unexpected token '(', "(node:1985"... is not valid JSON`
Rethrow with the full content of stderr so we can see what is appearing that is causing this failure
=> Improve debug message when json parsing fails in e2e tests

index.js
Fixes #383
Closes #384
Stylelint v16.13 and up raises a deprecation warning when you report with index but no endIndex.
Prettier may in some cases return a err.loc.end, use that if available, otherwise the error is a single character. It feels claim anything after that character is an error if prettier can't parse it.
=> Add endIndex to parsing error report call
